# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cancel_training_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(300, 100)
        MainWindow.setMinimumSize(QtCore.QSize(300, 100))
        MainWindow.setMaximumSize(QtCore.QSize(300, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_message = QtWidgets.QLabel(self.centralwidget)
        self.lbl_message.setGeometry(QtCore.QRect(50, 10, 200, 31))
        self.lbl_message.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_message.setAlignment(QtCore.Qt.Alignrightlight)
        self.lbl_message.setWordWrap(True)
        self.lbl_message.setObjectName("lbl_message")
        self.btn_no = QtWidgets.QPushButton(self.centralwidget)
        self.btn_no.setGeometry(QtCore.QRect(155, 50, 100, 25))
        self.btn_no.setObjectName("btn_no")
        self.btn_yes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_yes.setGeometry(QtCore.QRect(45, 50, 100, 25))
        self.btn_yes.setObjectName("btn_yes")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cancelar treinamento"))
        self.lbl_message.setText(_translate("MainWindow", "Deseja realmente cancelar o treinamento?"))
        self.btn_no.setText(_translate("MainWindow", "Não"))
        self.btn_yes.setText(_translate("MainWindow", "Sim"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
