# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inspection_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 420)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 40, 620, 350))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_message_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_message_2.setGeometry(QtCore.QRect(210, 10, 200, 25))
        self.lbl_message_2.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_message_2.setAlignment(QtCore.Qt.Alignrightlight)
        self.lbl_message_2.setWordWrap(True)
        self.lbl_message_2.setObjectName("lbl_message_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        SrcSize = QtGui.QScreen.availableGeometry(QtWidgets.QApplication.primaryScreen())
        frmX = (SrcSize.width() - MainWindow.width())/2
        frmY = (SrcSize.height() - MainWindow.height())/2
        MainWindow.move(frmX, frmY)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FaceRecognition-0.1.0"))
        self.lbl_message_2.setText(_translate("MainWindow", "Posicione o rosto no centro da tela"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
