# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listuserwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gpbox_user_list = QtWidgets.QGroupBox(self.centralwidget)
        self.gpbox_user_list.setGeometry(QtCore.QRect(10, 10, 580, 280))
        self.gpbox_user_list.setObjectName("gpbox_user_list")
        self.table_user_list = QtWidgets.QTableWidget(self.gpbox_user_list)
        self.table_user_list.setGeometry(QtCore.QRect(0, 30, 560, 250))
        self.table_user_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_user_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_user_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.table_user_list.setObjectName("table_user_list")
        self.table_user_list.setColumnCount(3)
        self.table_user_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_user_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_user_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_user_list.setHorizontalHeaderItem(2, item)
        self.btn_user_update = QtWidgets.QPushButton(self.centralwidget)
        self.btn_user_update.setGeometry(QtCore.QRect(600, 40, 90, 25))
        self.btn_user_update.setObjectName("btn_user_update")
        self.btn_user_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_user_delete.setGeometry(QtCore.QRect(600, 70, 90, 25))
        self.btn_user_delete.setObjectName("btn_user_delete")
        self.btn_back_page = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back_page.setGeometry(QtCore.QRect(600, 100, 90, 25))
        self.btn_back_page.setObjectName("btn_back_page")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        SrcSize = QtGui.QScreen.availableGeometry(QtWidgets.QApplication.primaryScreen())
        frmX = (SrcSize.width() - MainWindow.width())/2
        frmY = (SrcSize.height() - MainWindow.height())/2
        MainWindow.move(frmX, frmY)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gpbox_user_list.setTitle(_translate("MainWindow", "Lista de usuários"))
        item = self.table_user_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.table_user_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data de Nasc."))
        item = self.table_user_list.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tag RFIID"))
        self.btn_user_update.setText(_translate("MainWindow", "Atualizar"))
        self.btn_user_delete.setText(_translate("MainWindow", "Deletar"))
        self.btn_back_page.setText(_translate("MainWindow", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
