# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 110)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start_app = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_app.setGeometry(QtCore.QRect(170, 20, 150, 25))
        self.btn_start_app.setObjectName("btn_start_app")
        self.btn_train_network = QtWidgets.QPushButton(self.centralwidget)
        self.btn_train_network.setGeometry(QtCore.QRect(30, 20, 110, 25))
        self.btn_train_network.setObjectName("btn_train_network")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.action_user_create = QtWidgets.QAction(MainWindow)
        self.action_user_create.setObjectName("action_user_create")
        self.action_show_logs = QtWidgets.QAction(MainWindow)
        self.action_show_logs.setObjectName("action_show_logs")
        self.action_user_delete = QtWidgets.QAction(MainWindow)
        self.action_user_delete.setObjectName("action_user_delete")
        self.action_user_list = QtWidgets.QAction(MainWindow)
        self.action_user_list.setObjectName("action_user_list")
        self.menuMenu.addAction(self.action_user_create)
        self.menuMenu.addAction(self.action_user_list)
        self.menuMenu.addAction(self.action_show_logs)
        self.menubar.addAction(self.menuMenu.menuAction())
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        SrcSize = QtGui.QScreen.availableGeometry(QtWidgets.QApplication.primaryScreen())
        frmX = (SrcSize.width() - MainWindow.width())/2
        frmY = (SrcSize.height() - MainWindow.height())/2
        MainWindow.move(frmX, frmY)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FaceRecognition-0.1.0"))
        self.btn_start_app.setText(_translate("MainWindow", "Iniciar aplicação"))
        self.btn_train_network.setText(_translate("MainWindow", "Treinar rede"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.action_user_create.setText(_translate("MainWindow", "Criar usuário"))
        self.action_show_logs.setText(_translate("MainWindow", "Ver registros"))
        self.action_user_delete.setText(_translate("MainWindow", "Excluir usuário"))
        self.action_user_list.setText(_translate("MainWindow", "Listar usuário"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
